name: wake-cron
on:
  schedule:
    - cron: '*/25 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://befit-backend.herokuapp.com/api/wake' \
          --header 'Authorization: Bearer befitSecret123'
